EOS 13626: LogRotate Improvement: Remove logrotate custom script and move logrotate conf file at common place
Seagate/cortx-monitor pull request #211
Opened 2020-10-16 13:10 UTC by VijayThakkar132

## Problem Statement
<pre>
  <code>
    Story Ref (if any):
    EOS 13626: Logrotate improvement
  </code>
</pre>
## Problem Description
<pre>
  <code>
    Remove logrotate custom script and move conf file at common place
  </code>
</pre>
## Solution
<pre>
  <code>
    Removed earlier patch related to logrotate and moved conf file at /etc/logrotate_hourly/ as per Yash's inputs.
  </code>
</pre>
## Sanity testing on RPM done
<pre>
  <code>
    - [ ] Yes
  </code>
</pre>
## Unit/Manual Testing Description
<pre>
  <code>
    Please describe the tests that you ran to verify your changes.
  </code>
</pre>

2020-10-19 13:06 UTC, cdeshmukh commented
EOS-13626 was closed, why this PR now. can you tell me the need

2020-10-19 13:54 UTC, cdeshmukh approved these changes

2020-10-20 04:43 UTC, thavanathan approved these changes

2020-10-20 05:16 UTC, thavanathan requested changes
Please do not merge above PR right now. Seeing provisioner has reverted those changes https://github.com/Seagate/cortx-prvsnr/commit/33d5662f43ab517bb12ae846b39f37e0ad7f2375 in this PR.

2020-10-27 08:35 UTC, VijayThakkar132 commented
Changed conf dir path to inline with provisioner's changes. Now, This PR is good to merge

2020-10-28 05:15 UTC, thavanathan approved these changes

2020-10-29 13:09 UTC, indrajitzagade approved these changes

2020-10-30 05:45 UTC, merged