EOS-15736 : Change License text in SSPL rpms
Seagate/cortx-monitor pull request #260
Opened 2020-12-17 11:33 UTC by mohitpathak1

Signed-off-by: Mohit Pathak <mohit.pathak@seagate.com>

## Problem Statement
<pre>
  <code>
    Story Ref (if any):
    EOS-15736
  </code>
</pre>
## Problem Description
<pre>
  <code>
    RPM Validation result finds that the license value in cortx-sspl-test, cortx-sspl-cli and cortx-sspl rpms does not match with the expected value of "Seagate"
  </code>
</pre>
## Solution
<pre>
  <code>
    Changed the value in rpm spec files
  </code>
</pre>
## Sanity testing on RPM done
<pre>
  <code>
    - [ ] Yes
    - [ ] No
  </code>
</pre>
## Unit/Manual Testing Description
<pre>
  <code>
    Please describe the tests that you ran to verify your changes.
  </code>
</pre>

2020-12-17 12:48 UTC, cdeshmukh approved these changes

2020-12-17 17:11 UTC, saurabhkhanvilkar approved these changes

2020-12-17 17:12 UTC, saurabhkhanvilkar requested changes
I think let's do this change for main branch only...

2020-12-18 04:15 UTC, closed without merging

2020-12-18 04:15 UTC, mohitpathak1 commented
Closing this as not needed for cortx-1.0