EOS-23581: Corrected the cmd to add 'noop = true' in sspl_reinit.
Seagate/cortx-monitor pull request #503
Opened 2021-08-16 07:48 UTC by sumedhak27

Signed-off-by: Sumedh A. Kulkarni <sumedh.a.kulkarni@seagate.com>

## Problem Statement:
Puppet-agent is deleting the /etc/sudoers.d/sspl file since the cmd to write noop = true has some issues. correction regarding the same is needed.

## Solution Design:

## Coding:

* [ ] Did you follow coding standard and verified it with flake8? 

* [ ] Did your address all Codacy issues?

## Testing:

* [ ] Unittest updated and all unittests are passing?

* [ ] Sanity/Self tests are updated (if applicable)?

* [ ] Manual testing done covering happy path and non-happy path?

## Integration:

* [ ] If there is any interface change, did you communicate it to other components?
* [ ] If there is any interface change, other componenent gate gatekeepers are ready to accept the change?
* [ ] Did you complete deployment test if applicable?

## PR checklist:
* [ ] Did you add Jira number to the PR?

* [ ] DCO and cla-signed?

2021-08-16 07:55 UTC, sumedhak27 commented on low-level/framework/sspl_reinit
> +    fi
```shell
PUPPET_CONF="/etc/puppetlabs/puppet/puppet.conf"
[ -f $PUPPET_CONF ] && {
    grep -q "noop = false" $PUPPET_CONF && sed -i "s/noop = false/noop = true/" $PUPPET_CONF
    grep -q "noop = true" $PUPPET_CONF || echo "noop = true" >> $PUPPET_CONF
}
```
@mariyappanp is suggesting this simpler way considering modern shell script.
But I wanted to keep readability and consider the cases with multiple spaces before & after the '=' sign.
Everyone, please suggest which option we should go with.

2021-08-16 08:16 UTC, sumedhak27 commented on low-level/framework/sspl_reinit
> +    fi
```shell
PUPPET_CONF="/etc/puppetlabs/puppet/puppet.conf"
[ -f $PUPPET_CONF ] && {
    grep -q "noop = false" $PUPPET_CONF && sed -i "s/noop = false/noop = true/" $PUPPET_CONF
    grep -q "noop = true" $PUPPET_CONF || echo "noop = true" >> $PUPPET_CONF
}
```
@mariyappanp is suggesting this simpler way considering modern shell script.
But I wanted to keep readability and consider the cases with multiple spaces before & after the '=' sign.
Everyone, please suggest which option we should go with.

2021-08-16 12:49 UTC, mariyappanp approved these changes

2021-08-16 12:54 UTC, mariyappanp commented on low-level/framework/sspl_reinit
> +[ -f $PUPPET_CONF ] && conf "ini://$PUPPET_CONF" set "agent>noop=true"
This script is being called during sspl post_install. At that time, consider only cortx-utils post_install is just completed. 
In this case, does cortx-utils cli become usable once post_install stage completed for cortx-utils? If not, this approach can not work. Please make sure verified this on a clean setup. @sumedhak27 

cortx-utils conf cli will always be

2021-08-16 12:55 UTC, mariyappanp requested changes
Please confirm this.

2021-08-17 03:34 UTC, mariyappanp commented on low-level/framework/sspl_reinit
> +[ -f $PUPPET_CONF ] && conf "ini://$PUPPET_CONF" set "agent>noop=true"
Sumedh confirmed this test. Hence approving.

2021-08-17 03:34 UTC, mariyappanp approved these changes

2021-08-17 03:41 UTC, shriya-deshmukh approved these changes

2021-08-17 08:21 UTC, cdeshmukh approved these changes

2021-08-17 18:20 UTC, cdeshmukh commented
Vm deployment success http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Cortx-Deployment/job/SSPL/572/

2021-08-17 18:22 UTC, merged